"""initial schema

Revision ID: 1cb4ff4ac995
Revises:
Create Date: 2026-08-25 08:26:45.200147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1cb4ff4ac995'
down_revision = None
branch_labels = None
depends_on = None

offer_type = postgresql.ENUM("percentage", "fixed", name="offer_type", create_type=False)
session_outcome = postgresql.ENUM(
    "active", "converted", "abandoned", "failed", name="session_outcome", create_type=False
)
policy_decision = postgresql.ENUM(
    "allow", "deny", "require_confirmation", name="policy_decision", create_type=False
)
event_type = postgresql.ENUM(
    "session_started", "intent_captured", "products_shown", "product_selected",
    "upsell_offered", "upsell_accepted", "checkout_started", "payment_succeeded",
    name="event_type", create_type=False,
)
order_status = postgresql.ENUM(
    "created", "pending_payment", "paid", "failed", "cancelled", "expired",
    name="order_status", create_type=False,
)
payment_status = postgresql.ENUM(
    "created", "authorized", "captured", "failed", "refunded",
    name="payment_status", create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    for enum in (offer_type, session_outcome, policy_decision, event_type, order_status, payment_status):
        enum.create(bind, checkfirst=True)
    op.create_table('eval_runs',
    sa.Column('simulated', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('embedding_provider', sa.String(length=120), nullable=False),
    sa.Column('catalog_hash', sa.String(length=64), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('max_cart_value_paise', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('eval_sessions',
    sa.Column('eval_run_id', sa.UUID(), nullable=False),
    sa.Column('arm', sa.String(length=80), nullable=False),
    sa.Column('persona_id', sa.String(length=80), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('offer_type', offer_type, nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('min_cart_paise', sa.BigInteger(), nullable=False),
    sa.Column('max_discount_paise', sa.BigInteger(), nullable=True),
    sa.Column('applicable_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('products',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('subcategory', sa.String(length=80), nullable=False),
    sa.Column('price_paise', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_products_attrs_gin', 'products', ['attrs'], unique=False, postgresql_using='gin')
    op.create_index('ix_products_merchant_category', 'products', ['merchant_id', 'category'], unique=False)
    op.create_index('ix_products_price_paise', 'products', ['price_paise'], unique=False)
    op.create_index('ix_products_search_tsv_gin', 'products', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_table('sessions',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('outcome', session_outcome, nullable=False),
    sa.Column('budget_paise', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_steps',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_rule_id', sa.String(length=80), nullable=True),
    sa.Column('policy_decision', policy_decision, nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_agent_steps_session_step', 'agent_steps', ['session_id', 'step_no'], unique=True)
    op.create_table('carts',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('subtotal_paise', sa.BigInteger(), nullable=False),
    sa.Column('discount_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('confirmation_tokens',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('cart_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_embeddings',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', postgresql.ARRAY(sa.REAL()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_product_embedding_content', 'product_embeddings', ['product_id', 'model', 'content_hash'], unique=True)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('colour', sa.String(length=40), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_product_variants_product_size', 'product_variants', ['product_id', 'size'], unique=False)
    op.create_index('uq_product_variants_product_size', 'product_variants', ['product_id', 'size'], unique=True)
    op.create_table('session_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', event_type, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_events_session_created', 'session_events', ['session_id', 'created_at'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_cart_items_cart_variant', 'cart_items', ['cart_id', 'variant_id'], unique=True)
    op.create_table('orders',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', order_status, nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=120), nullable=True),
    sa.Column('cart_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=120), nullable=False),
    sa.Column('status', payment_status, nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_index('uq_cart_items_cart_variant', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('ix_session_events_session_created', table_name='session_events')
    op.drop_table('session_events')
    op.drop_index('uq_product_variants_product_size', table_name='product_variants')
    op.drop_index('ix_product_variants_product_size', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('uq_product_embedding_content', table_name='product_embeddings')
    op.drop_table('product_embeddings')
    op.drop_table('messages')
    op.drop_table('confirmation_tokens')
    op.drop_table('carts')
    op.drop_index('uq_agent_steps_session_step', table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_table('sessions')
    op.drop_index('ix_products_search_tsv_gin', table_name='products', postgresql_using='gin')
    op.drop_index('ix_products_price_paise', table_name='products')
    op.drop_index('ix_products_merchant_category', table_name='products')
    op.drop_index('ix_products_attrs_gin', table_name='products', postgresql_using='gin')
    op.drop_table('products')
    op.drop_table('offers')
    op.drop_table('eval_sessions')
    op.drop_table('merchants')
    op.drop_table('eval_runs')
    bind = op.get_bind()
    for enum in (payment_status, order_status, event_type, policy_decision, session_outcome, offer_type):
        enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
