/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cart/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Cart
         * @description Mint a cart-bound token only in response to an explicit user UI action.
         */
        post: operations["confirm_cart_api_v1_cart_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Products
         * @description Return products after SQL constraints, hybrid RRF and transparent re-ranking.
         */
        get: operations["search_products_api_v1_catalog_products_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfirmCartRequest */
        ConfirmCartRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "create_razorpay_order" | "place_order";
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** ConfirmCartResponse */
        ConfirmCartResponse: {
            /** Expires At */
            expires_at: string;
            /** Token */
            token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ScoreBreakdownResponse */
        ScoreBreakdownResponse: {
            /** Business */
            business: number;
            /** Final */
            final: number;
            /** Lexical */
            lexical: number;
            /** Rrf */
            rrf: number;
            /** Semantic */
            semantic: number;
        };
        /** SearchHitResponse */
        SearchHitResponse: {
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
            /** Available Sizes */
            available_sizes: string[];
            /** Brand */
            brand: string;
            /** Category */
            category: string;
            /** Match Reasons */
            match_reasons: string[];
            /** Price Paise */
            price_paise: number;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            score_breakdown: components["schemas"]["ScoreBreakdownResponse"];
            /** Sku */
            sku: string;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    confirm_cart_api_v1_cart_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmCartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmCartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_products_api_v1_catalog_products_search_get: {
        parameters: {
            query: {
                q: string;
                max_price_paise?: number | null;
                category?: string | null;
                in_stock?: boolean;
                size?: string | null;
                brand?: string | null;
                gender?: string | null;
                arch_support?: string[] | null;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHitResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
